name: Call DevOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  use-central:
    uses: ${{ secrets.G_UserName }}/${{ secrets.Folder_Name }}/.github/workflows/Build.yml@main

    with:
      app_name: redan # repository name must be lowercase

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    


  