name: Call DevOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  use-central:
    uses: redasaad123/CI-CD-GitHub-Action/.github/workflows/Build.yml@main

    with:
      app_name: redan # repository name must be lowercase

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    


  